package Admin Panel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ArfaatAli
 */

import java.sql.*;
import java.util.*;
import java.text.*;
import java.util.Date;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;



public class View_User extends javax.swing.JFrame {
Connection con =null;
ResultSet rs =null;
PreparedStatement pst = null;
String sql =null;

    /**
     * Creates new form View_User
     */
    public View_User() {
        initComponents();
     //   con=Javaconnect.ConnectDb();
     
    }
   
 
  
private void Update_Table_ID()
{
    try
    {
        String srch= id_search.getText();
        int a= Integer.parseInt(srch);
        sql = "SELECT * FROM userdetails WHERE  user_id = " + a;
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SMS_DB","root","root");
    Class.forName("com.mysql.jdbc.Driver");
pst = con.prepareStatement(sql);
rs=pst.executeQuery();
User_Table.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }
             
}
private void Update_Table_Name()
{
    try
    {
        String srch= name_srch.getText();
        sql = "SELECT * FROM userdetails WHERE  name = ? ";
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SMS_DB","root","root");
    Class.forName("com.mysql.jdbc.Driver");
pst = con.prepareStatement(sql);
pst.setString(1,srch);
rs=pst.executeQuery();
User_Table.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }      
}

private void Update_Table_mail()
{
    // SELECT * FROM addresses WHERE MATCH(email) AGAINST('"name@example.com"' IN BOOLEAN MODE)
    try
    {
        String srch= mail_scrh.getText();
        sql = "SELECT * FROM userdetails WHERE  emailid = ?" ;
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SMS_DB","root","root");
    Class.forName("com.mysql.jdbc.Driver");
pst = con.prepareStatement(sql);
pst.setString(1,srch);
rs=pst.executeQuery();
User_Table.setModel(DbUtils.resultSetToTableModel(rs));
    }
    catch(Exception e)
            {
                JOptionPane.showMessageDialog(null, e);
            }      
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        name_srch = new javax.swing.JTextField();
        mail_scrh = new javax.swing.JTextField();
        id_search = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        User_Table = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        pwd = new javax.swing.JTextField();
        contact1 = new javax.swing.JTextField();
        user_type = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Search By User Name: ");

        jLabel2.setText("Search By User Email : ");

        jLabel3.setText("Search By User ID: ");

        id_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_searchActionPerformed(evt);
            }
        });

        search_btn.setText("Search");
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });

        User_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "ID", "Password", "Eamil ID", "Contact", "User Tytpe", "Reg Date", "Modify Date"
            }
        ));
        User_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                User_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(User_Table);

        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel4.setText("Password :");

        jLabel5.setText("Contact : ");

        jLabel6.setText("User Type :");

        jLabel8.setText("Developed By BC110401204");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mail_scrh, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(name_srch)
                            .addComponent(id_search, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_type, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(251, 251, 251))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(name_srch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pwd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(mail_scrh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(id_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(user_type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search_btn)
                    .addComponent(delete)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new main().setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void id_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_searchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_searchActionPerformed
private void Reset()
 {
     name_srch.setText("");
            mail_scrh.setText("");
            id_search.setText("");
            pwd.setText("");
            contact1.setText("");
            user_type.setText("");
 }
    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        String srch= id_search.getText();
        String srch1= name_srch.getText();
        String srch2= mail_scrh.getText();
        if(!srch1.equals(""))
        {
        Update_Table_Name();
        }
        else if (!srch2.equals(""))
        {
        Update_Table_mail();      
        }
        else if (!srch.equals(""))
        {
        Update_Table_ID();
        }
        
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try
        {
            String srch = id_search.getText();
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SMS_DB","root","root");
            Class.forName("com.mysql.jdbc.Driver");           
            String sql = "delete from userdetails where user_id = ? ";
            pst = con.prepareStatement(sql);
            pst.setString(1, srch);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Deleted");
            Update_Table_ID();
            Reset();
            
        }
    catch(Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
        
    }//GEN-LAST:event_deleteActionPerformed
String dt;
    private void User_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_User_TableMouseClicked
        // TODO add your handling code here:
        try
        {
            int row = User_Table.getSelectedRow();
            String table_click = (User_Table.getModel().getValueAt(row, 1).toString());
            // String srch = id_search.getText();
            Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SMS_DB","root","root");
            Class.forName("com.mysql.jdbc.Driver");           
            String sql = "select * from userdetails where user_id = '" +table_click+ "'  ";
            pst = con.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next())
            {
            String nm = rs.getString("name");
            name_srch.setText(nm);
            String mail = rs.getString("emailid");
            mail_scrh.setText(mail); 
            String id = rs.getString("user_id");
            id_search.setText(id);
            String pwd1 = rs.getString("password");
            pwd.setText(pwd1);
            String contact = rs.getString("contact");
            contact1.setText(contact);
            String type = String.valueOf(rs.getString("usertypeid"));
            user_type.setText(type);
            dt = String.valueOf(rs.getString("registerationdate"));
            
            }
         }
    catch(Exception e) 
            {
                JOptionPane.showMessageDialog(null, e);
            }
    }//GEN-LAST:event_User_TableMouseClicked
Date date = new Date();
    SimpleDateFormat ft =  new SimpleDateFormat ("yyyy-MM-dd ");
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
    Connection con= (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/SMS_DB","root","root");
    Class.forName("com.mysql.jdbc.Driver");
    String nm =name_srch.getText();
    String id = id_search.getText();
    String pwd12 = pwd.getText();
    String ml =mail_scrh.getText();
    String cn = contact1.getText();
    String type = user_type.getText();
    
    String sql="UPDATE userdetails set name = '"+nm+ "',user_id = '"+id+"', password = '"+pwd12+"',emailid = '"+ml+"',"
            + " contact = '"+cn+"', usertypeid = '"+type+"',registerationdate = '"+dt+"',modifydate = '"+ft.format(date)+"' where user_id = '"+id+"'";
 
    pst = con.prepareStatement(sql);
    pst.execute();
     Update_Table_ID();
    Reset();
    
    
    JOptionPane.showMessageDialog(this, "Update successfully ");
}
catch (Exception e){
JOptionPane.showMessageDialog(this, e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable User_Table;
    private javax.swing.JTextField contact1;
    private javax.swing.JButton delete;
    private javax.swing.JTextField id_search;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mail_scrh;
    private javax.swing.JTextField name_srch;
    private javax.swing.JTextField pwd;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField user_type;
    // End of variables declaration//GEN-END:variables
}
